export default {
  "@primary-color": "@blue-6",
  "@info-color": "@blue-6",
  "@success-color": "@green-6",
  "@processing-color": "@blue-6",
  "@error-color": "@red-6",
  "@highlight-color": "@red-6",
  "@warning-color": "@gold-6",
  "@normal-color": "#d9d9d9",
  "@white": "#fff",
  "@black": "#000",
  "@primary-1": "color(~`colorPalette('@{primary-color}', 1) `)",
  "@primary-2": "color(~`colorPalette('@{primary-color}', 2) `)",
  "@primary-3": "color(~`colorPalette('@{primary-color}', 3) `)",
  "@primary-4": "color(~`colorPalette('@{primary-color}', 4) `)",
  "@primary-5": "color(\n  ~`colorPalette('@{primary-color}', 5) `\n)",
  "@primary-6": "@primary-color",
  "@primary-7": "color(~`colorPalette('@{primary-color}', 7) `)",
  "@primary-8": "color(~`colorPalette('@{primary-color}', 8) `)",
  "@primary-9": "color(~`colorPalette('@{primary-color}', 9) `)",
  "@primary-10": "color(~`colorPalette('@{primary-color}', 10) `)",
  "@body-background": "#fff",
  "@component-background": "#fff",
  "@heading-color": "fade(@black, 85%)",
  "@text-color": "fade(@black, 65%)",
  "@text-color-secondary": "fade(@black, 45%)",
  "@text-color-inverse": "@white",
  "@icon-color-hover": "fade(@black, 75%)",
  "@heading-color-dark": "fade(@white, 100%)",
  "@text-color-dark": "fade(@white, 85%)",
  "@text-color-secondary-dark": "fade(@white, 65%)",
  "@item-active-bg": "@primary-1",
  "@item-hover-bg": "@primary-1",
  "@link-color": "@primary-color",
  "@link-hover-color": "color(~`colorPalette('@{link-color}', 5) `)",
  "@link-active-color": "color(~`colorPalette('@{link-color}', 7) `)",
  "@border-color-base": "hsv(0, 0, 85%)",
  "@border-color-split": "hsv(0, 0, 91%)",
  "@border-color-inverse": "@white",
  "@outline-color": "@primary-color",
  "@background-color-light": "hsv(0, 0, 98%)",
  "@background-color-base": "hsv(0, 0, 96%)",
  "@disabled-color": "fade(#000, 25%)",
  "@disabled-bg": "@background-color-base",
  "@disabled-color-dark": "fade(#fff, 35%)",
  "@shadow-color": "rgba(0, 0, 0, 0.15)",
  "@shadow-color-inverse": "@component-background",
  "@btn-primary-color": "#fff",
  "@btn-primary-bg": "@primary-color",
  "@btn-default-color": "@text-color",
  "@btn-default-bg": "#fff",
  "@btn-default-border": "@border-color-base",
  "@btn-danger-color": "@error-color",
  "@btn-danger-bg": "@background-color-base",
  "@btn-danger-border": "@border-color-base",
  "@btn-disable-color": "@disabled-color",
  "@btn-disable-bg": "@disabled-bg",
  "@btn-disable-border": "@border-color-base",
  "@btn-group-border": "@primary-5",
  "@checkbox-color": "@primary-color",
  "@checkbox-check-color": "#fff",
  "@radio-dot-color": "@primary-color",
  "@radio-button-bg": "@btn-default-bg",
  "@radio-button-color": "@btn-default-color",
  "@radio-button-hover-color": "@primary-5",
  "@radio-button-active-color": "@primary-7",
  "@layout-body-background": "#f0f2f5",
  "@layout-header-background": "#001529",
  "@layout-footer-background": "@layout-body-background",
  "@layout-sider-background": "@layout-header-background",
  "@layout-trigger-background": "#002140",
  "@layout-trigger-color": "#fff",
  "@layout-sider-background-light": "#fff",
  "@layout-trigger-background-light": "#fff",
  "@layout-trigger-color-light": "@text-color",
  "@label-required-color": "@highlight-color",
  "@label-color": "@heading-color",
  "@input-placeholder-color": "hsv(0, 0, 75%)",
  "@input-color": "@text-color",
  "@input-border-color": "@border-color-base",
  "@input-bg": "#fff",
  "@input-number-handler-active-bg": "#f4f4f4",
  "@input-addon-bg": "@background-color-light",
  "@input-hover-border-color": "@primary-color",
  "@input-disabled-bg": "@disabled-bg",
  "@select-border-color": "@border-color-base",
  "@tooltip-color": "#fff",
  "@tooltip-bg": "rgba(0, 0, 0, 0.75)",
  "@tooltip-arrow-color": "@tooltip-bg",
  "@popover-bg": "#fff",
  "@popover-color": "@text-color",
  "@popover-arrow-color": "@popover-bg",
  "@popover-arrow-outer-color": "@popover-bg",
  "@modal-header-bg": "@component-background",
  "@modal-mask-bg": "fade(@black, 65%)",
  "@progress-default-color": "@processing-color",
  "@progress-remaining-color": "@background-color-base",
  "@progress-text-color": "@text-color",
  "@menu-bg": "@component-background",
  "@menu-popup-bg": "@component-background",
  "@menu-item-color": "@text-color",
  "@menu-highlight-color": "@primary-color",
  "@menu-item-active-bg": "@item-active-bg",
  "@menu-item-group-title-color": "@text-color-secondary",
  "@menu-dark-color": "@text-color-secondary-dark",
  "@menu-dark-bg": "@layout-header-background",
  "@menu-dark-arrow-color": "#fff",
  "@menu-dark-submenu-bg": "#000c17",
  "@menu-dark-highlight-color": "#fff",
  "@menu-dark-item-active-bg": "@primary-color",
  "@table-header-bg": "@background-color-light",
  "@table-header-color": "@heading-color",
  "@table-header-sort-bg": "@background-color-base",
  "@table-body-sort-bg": "rgba(0, 0, 0, 0.01)",
  "@table-row-hover-bg": "@primary-1",
  "@table-selected-row-bg": "#fafafa",
  "@table-expanded-row-bg": "#fbfbfb",
  "@tag-default-bg": "@background-color-light",
  "@tag-default-color": "@text-color",
  "@time-picker-selected-bg": "@background-color-base",
  "@badge-text-color": "@component-background",
  "@rate-star-color": "@yellow-6",
  "@rate-star-bg": "@border-color-split",
  "@card-head-color": "@heading-color",
  "@card-head-background": "transparent",
  "@card-actions-background": "@background-color-light",
  "@card-background": "#cfd8dc",
  "@comment-author-name-color": "@text-color-secondary",
  "@comment-author-time-color": "#ccc",
  "@comment-action-color": "@text-color-secondary",
  "@comment-action-hover-color": "#595959",
  "@tabs-card-head-background": "@background-color-light",
  "@tabs-card-active-color": "@primary-color",
  "@tabs-ink-bar-color": "@primary-color",
  "@tabs-highlight-color": "@primary-color",
  "@tabs-hover-color": "@primary-5",
  "@tabs-active-color": "@primary-7",
  "@back-top-color": "#fff",
  "@back-top-bg": "@text-color-secondary",
  "@back-top-hover-bg": "@text-color",
  "@avatar-bg": "#ccc",
  "@avatar-color": "#fff",
  "@switch-color": "@primary-color",
  "@switch-shadow-color": "fade(#00230b, 20%)",
  "@breadcrumb-base-color": "@text-color-secondary",
  "@breadcrumb-last-item-color": "@text-color",
  "@breadcrumb-link-color": "@text-color-secondary",
  "@breadcrumb-link-color-hover": "@primary-5",
  "@breadcrumb-separator-color": "@text-color-secondary",
  "@slider-rail-background-color": "@background-color-base",
  "@slider-rail-background-color-hover": "#e1e1e1",
  "@slider-track-background-color": "@primary-3",
  "@slider-track-background-color-hover": "@primary-4",
  "@slider-handle-color": "@primary-3",
  "@slider-handle-color-hover": "@primary-4",
  "@slider-handle-color-focus": "tint(@primary-color, 20%)",
  "@slider-handle-color-focus-shadow": "fade(@primary-color, 20%)",
  "@slider-handle-color-tooltip-open": "@primary-color",
  "@slider-dot-border-color": "@border-color-split",
  "@slider-dot-border-color-active": "tint(@primary-color, 50%)",
  "@slider-disabled-color": "@disabled-color",
  "@slider-disabled-background-color": "@component-background",
  "@tree-directory-selected-color": "#fff",
  "@tree-directory-selected-bg": "@primary-color",
  "@collapse-header-bg": "@background-color-light",
  "@collapse-content-bg": "@component-background",
  "@skeleton-color": "#f2f2f2",
  "@transfer-disabled-bg": "@disabled-bg",
  "@alert-success-border-color": "~`colorPalette('@{success-color}', 3) `",
  "@alert-success-bg-color": "~`colorPalette('@{success-color}', 1) `",
  "@alert-success-icon-color": "@success-color",
  "@alert-info-border-color": "~`colorPalette('@{info-color}', 3) `",
  "@alert-info-bg-color": "~`colorPalette('@{info-color}', 1) `",
  "@alert-info-icon-color": "@info-color",
  "@alert-warning-border-color": "~`colorPalette('@{warning-color}', 3) `",
  "@alert-warning-bg-color": "~`colorPalette('@{warning-color}', 1) `",
  "@alert-warning-icon-color": "@warning-color",
  "@alert-error-border-color": "~`colorPalette('@{error-color}', 3) `",
  "@alert-error-bg-color": "~`colorPalette('@{error-color}', 1) `",
  "@alert-error-icon-color": "@error-color",
  "@list-header-background": "transparent",
  "@list-footer-background": "transparent",

  "@secondary-color": "#ccc"
};
